/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package board.game.ui;

import board.game.util.XIcon;

/**
 *
 * @author LAPTOP LE SON
 */
public class BoardGameJFrame extends javax.swing.JFrame implements BoardGameController {

    /**
     * Creates new form boardgameJframe
     */
    
  public BoardGameJFrame(String userId,String fullName, boolean isManager) {
    initComponents();
     lblUserID.setText("User ID: " + userId);
    lblUser.setText("Chào mừng: " + fullName);
    this.isManager = isManager;
    btnUserManager.setVisible(isManager);
    btnHistoryManager.setVisible(isManager);
    btnChangePassword.setVisible(true); 
     lblName.setText(isManager ? "Admin" : "Player");
       setLocationRelativeTo(null);
}
  
private boolean isManager;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnFlappy = new javax.swing.JButton();
        btnPacman = new javax.swing.JButton();
        btnShot = new javax.swing.JButton();
        btnSnake = new javax.swing.JButton();
        btnTank = new javax.swing.JButton();
        btnBom = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnHistoryManager = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        lblName.setText("user");
        jPanel5.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Thoát");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 137, -1));

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblUser.setForeground(new java.awt.Color(51, 51, 51));
        lblUser.setText("Chào mừng: (User)");
        jPanel5.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        btnFlappy.setBackground(new java.awt.Color(153, 0, 102));
        btnFlappy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFlappy.setForeground(new java.awt.Color(255, 255, 255));
        btnFlappy.setText("Flappy Bird");
        btnFlappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlappyActionPerformed(evt);
            }
        });
        jPanel5.add(btnFlappy, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 160, 50));

        btnPacman.setBackground(new java.awt.Color(153, 0, 102));
        btnPacman.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPacman.setForeground(new java.awt.Color(255, 255, 255));
        btnPacman.setText("PacMan");
        btnPacman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacmanActionPerformed(evt);
            }
        });
        jPanel5.add(btnPacman, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 160, 50));

        btnShot.setBackground(new java.awt.Color(153, 0, 102));
        btnShot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShot.setForeground(new java.awt.Color(255, 255, 255));
        btnShot.setText("Meteor");
        btnShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShotActionPerformed(evt);
            }
        });
        jPanel5.add(btnShot, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 160, 50));

        btnSnake.setBackground(new java.awt.Color(153, 0, 102));
        btnSnake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSnake.setForeground(new java.awt.Color(255, 255, 255));
        btnSnake.setText("Rắn Săn Mồi");
        btnSnake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnakeActionPerformed(evt);
            }
        });
        jPanel5.add(btnSnake, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 160, 50));

        btnTank.setBackground(new java.awt.Color(153, 0, 102));
        btnTank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTank.setForeground(new java.awt.Color(255, 255, 255));
        btnTank.setText("Bắn Xe Tăng");
        btnTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTankActionPerformed(evt);
            }
        });
        jPanel5.add(btnTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 160, 50));

        btnBom.setBackground(new java.awt.Color(153, 0, 102));
        btnBom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBom.setForeground(new java.awt.Color(255, 255, 255));
        btnBom.setText("Dò Mìn");
        btnBom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBomActionPerformed(evt);
            }
        });
        jPanel5.add(btnBom, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 160, 50));

        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChangePassword.setText("Đổi mật khẩu");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel5.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 200, 30));

        btnUserManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUserManager.setText("Quản lý người dùng");
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        jPanel5.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/Pacman.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/flappy-bird-sprite.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/snake.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/bomb.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/spaceship.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/xetang.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 410, -1, -1));

        btnHistoryManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistoryManager.setText("Quản lý lịch sử");
        btnHistoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryManagerActionPerformed(evt);
            }
        });
        jPanel5.add(btnHistoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/avatar_resized_150x150.jpg"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        lblUserID.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblUserID.setText("User ID");
        jPanel5.add(lblUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/background home.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTankActionPerformed
        // TODO add your handling code here:
        this.showTank();
    }//GEN-LAST:event_btnTankActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        this.showChangePasswordJDilog(this);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        // TODO add your handling code here:
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnHistoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryManagerActionPerformed
        // TODO add your handling code here:
        this.showHistoryManagerJDialog(this);
    }//GEN-LAST:event_btnHistoryManagerActionPerformed

    private void btnFlappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlappyActionPerformed
        // TODO add your handling code here:
        this.showFlappyBirdGame();
    }//GEN-LAST:event_btnFlappyActionPerformed

    private void btnSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnakeActionPerformed
        // TODO add your handling code here:
        this.showRanSanMoiGame();
    }//GEN-LAST:event_btnSnakeActionPerformed

    private void btnShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShotActionPerformed
        // TODO add your handling code here:
        this.showBanGaGame();
    }//GEN-LAST:event_btnShotActionPerformed

    private void btnPacmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacmanActionPerformed
        // TODO add your handling code here:
        this.showPacManGame();
    }//GEN-LAST:event_btnPacmanActionPerformed

    private void btnBomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBomActionPerformed
        // TODO add your handling code here:
        this.showDoMin();
    }//GEN-LAST:event_btnBomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false); // Ẩn khung hiện tại nếu cần

    LoginJDialog login = new LoginJDialog(this, true); // Tạo dialog login mới
    login.setLocationRelativeTo(null); // Đặt giữa màn hình
    login.setVisible(true); // Hiển thị hộp thoại login

    if (login.loginSuccessful) {
        // Nếu đăng nhập thành công, tạo lại JFrame với thông tin mới
        new BoardGameJFrame(login.UserId(), login.getFullName(), login.isManager()).setVisible(true);
        this.dispose(); // Đóng khung cũ (nếu bạn muốn)
    } else {
        System.exit(0); // Thoát nếu không login được
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(() -> {
        LoginJDialog dialog = new LoginJDialog(null, true); // mở form login
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

        if (dialog.loginSuccessful) {
            // gọi constructor có tham số đầy đủ
            new BoardGameJFrame(dialog.UserId(),dialog.getFullName(), dialog.isManager()).setVisible(true);
        } else {
            System.exit(0);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBom;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnFlappy;
    private javax.swing.JButton btnHistoryManager;
    private javax.swing.JButton btnPacman;
    private javax.swing.JButton btnShot;
    private javax.swing.JButton btnSnake;
    private javax.swing.JButton btnTank;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserID;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
 this.setIconImage(XIcon.getIcon("Pacman.png").getImage());
        //để hiện thị icon trên góc của view khi chạy
        this.setLocationRelativeTo(null);
                this.showLoginJDialog(this);
        this.showWelcomeJDialog(this);
    }
}
