/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package board.game.ui;

import board.game.util.XIcon;

/**
 *
 * @author LAPTOP LE SON
 */
public class BoardGameJFrame extends javax.swing.JFrame implements BoardGameController {

    /**
     * Creates new form boardgameJframe
     */
    public BoardGameJFrame() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnDoiDiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnFlappy = new javax.swing.JButton();
        btnPacman = new javax.swing.JButton();
        btnShot = new javax.swing.JButton();
        btnSnake = new javax.swing.JButton();
        btnTank = new javax.swing.JButton();
        btnBom = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnHistoryManager = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel1.setText("user");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Đăng xuất");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 137, -1));

        btnDoiDiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiDiem.setText("Đổi điểm");
        btnDoiDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiDiemActionPerformed(evt);
            }
        });
        jPanel5.add(btnDoiDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 170, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chào mừng: (User)");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        btnFlappy.setBackground(new java.awt.Color(153, 0, 102));
        btnFlappy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFlappy.setForeground(new java.awt.Color(255, 255, 255));
        btnFlappy.setText("Flappy Bird");
        btnFlappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlappyActionPerformed(evt);
            }
        });
        jPanel5.add(btnFlappy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 137, -1));

        btnPacman.setBackground(new java.awt.Color(153, 0, 102));
        btnPacman.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPacman.setForeground(new java.awt.Color(255, 255, 255));
        btnPacman.setText("PacMan");
        btnPacman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacmanActionPerformed(evt);
            }
        });
        jPanel5.add(btnPacman, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 137, -1));

        btnShot.setBackground(new java.awt.Color(153, 0, 102));
        btnShot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShot.setForeground(new java.awt.Color(255, 255, 255));
        btnShot.setText("Bắn Gà");
        btnShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShotActionPerformed(evt);
            }
        });
        jPanel5.add(btnShot, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 137, -1));

        btnSnake.setBackground(new java.awt.Color(153, 0, 102));
        btnSnake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSnake.setForeground(new java.awt.Color(255, 255, 255));
        btnSnake.setText("Rắn Săn Mồi");
        btnSnake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnakeActionPerformed(evt);
            }
        });
        jPanel5.add(btnSnake, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 137, -1));

        btnTank.setBackground(new java.awt.Color(153, 0, 102));
        btnTank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTank.setForeground(new java.awt.Color(255, 255, 255));
        btnTank.setText("Bắn Xe Tăng");
        btnTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTankActionPerformed(evt);
            }
        });
        jPanel5.add(btnTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 140, -1));

        btnBom.setBackground(new java.awt.Color(153, 0, 102));
        btnBom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBom.setForeground(new java.awt.Color(255, 255, 255));
        btnBom.setText("Dò Mìn");
        btnBom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBomActionPerformed(evt);
            }
        });
        jPanel5.add(btnBom, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 137, -1));

        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangePassword.setText("Đổi mật khẩu");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel5.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 137, -1));

        btnUserManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserManager.setText("Quản lý người dùng");
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        jPanel5.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 170, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/Pacman.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/flappy-bird-sprite.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/snake.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/bomb.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/chicken.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/xetang.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        btnHistoryManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistoryManager.setText("Quản lý lịch sử");
        btnHistoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryManagerActionPerformed(evt);
            }
        });
        jPanel5.add(btnHistoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board/game/icons/User (1).png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTankActionPerformed
        // TODO add your handling code here:
        this.showTank();
    }//GEN-LAST:event_btnTankActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        this.showChangePasswordJDilog(this);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnDoiDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiDiemActionPerformed
        // TODO add your handling code here:
        this.showDoidiemJDialog(this);
    }//GEN-LAST:event_btnDoiDiemActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        // TODO add your handling code here:
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnHistoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryManagerActionPerformed
        // TODO add your handling code here:
        this.showHistoryManagerJDialog(this);
    }//GEN-LAST:event_btnHistoryManagerActionPerformed

    private void btnFlappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlappyActionPerformed
        // TODO add your handling code here:
        this.showFlappyBirdGame();
    }//GEN-LAST:event_btnFlappyActionPerformed

    private void btnSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnakeActionPerformed
        // TODO add your handling code here:
        this.showRanSanMoiGame();
    }//GEN-LAST:event_btnSnakeActionPerformed

    private void btnShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShotActionPerformed
        // TODO add your handling code here:
        this.showBanGaGame();
    }//GEN-LAST:event_btnShotActionPerformed

    private void btnPacmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacmanActionPerformed
        // TODO add your handling code here:
        this.showPacManGame();
    }//GEN-LAST:event_btnPacmanActionPerformed

    private void btnBomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBomActionPerformed
        // TODO add your handling code here:
        this.showDoMin();
    }//GEN-LAST:event_btnBomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBom;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDoiDiem;
    private javax.swing.JButton btnFlappy;
    private javax.swing.JButton btnHistoryManager;
    private javax.swing.JButton btnPacman;
    private javax.swing.JButton btnShot;
    private javax.swing.JButton btnSnake;
    private javax.swing.JButton btnTank;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
 this.setIconImage(XIcon.getIcon("Pacman.png").getImage());
        //để hiện thị icon trên góc của view khi chạy
        this.setLocationRelativeTo(null);
        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);
        this.showSignUpJDialog(this);
    }
}
